// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Event__FormController from "./event/form_controller"
application.register("event--form", Event__FormController)

import EventMapController from "./event_map_controller"
application.register("event-map", EventMapController)

import EventUserInterestedButtonController from "./event_user_interested_button_controller"
application.register("event-user-interested-button", EventUserInterestedButtonController)

import FlashMessageController from "./flash_message_controller"
application.register("flash-message", FlashMessageController)

import MapViewController from "./map_view_controller"
application.register("map-view", MapViewController)

import ReportProblemFormController from "./report_problem_form_controller"
application.register("report-problem-form", ReportProblemFormController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ShortUrlController from "./short_url_controller"
application.register("short-url", ShortUrlController)

import UserController from "./user_controller"
application.register("user", UserController)

import VideoController from "./video_controller"
application.register("video", VideoController)

import HwComboboxController from "@josefarias/hotwire_combobox"
application.register("hw-combobox", HwComboboxController)
