image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    before: docker-compose up -d
    init: >
      bundle install &&
      yarn install &&
      bundle exec rails db:setup &&
      gp sync-done setup
    command: >
      docker-compose up -d &&
      gp sync-done setup &&
      exit

  - name: Delayed Job
    command: >
      gp sync-await setup &&
      bundle exec bin/rake jobs:work

  - name: Webpacker
    command: >
      gp sync-await setup &&
      bundle exec bin/webpack-dev-server

  - name: Rails server
    command: >
      gp sync-await setup &&
      bundle exec bin/rails server -b 0.0.0.0 -p 3000 -e development -b 'ssl://0.0.0.0:3000?key=./certs/localhost.key&cert=./certs/localhost.crt'

ports:
  - port: 3000
    visibility: public
  - port: 3035
    visibility: private
  - port: 6379
    visibility: private
  - port: 5432
    visibility: private

vscode:
  extensions:
    - rebornix.ruby
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - mhutchie.git-graph

github:
  prebuilds:
    master: true
    branches: true
