image:
  file: .gitpod.Dockerfile

tasks:
  - before: docker-compose up -d
  - init: >
      bundle install &&
      yarn install &&
      bundle exec rails db:setup &&
      bundle exec rails test
  - command: foreman start

ports:
  - port: 3000
    visibility: public
  - port: 3035
    visibility: private
  - port: 6379
    visibility: private
  - port: 5432
    visibility: private

vscode:
  extensions:
    - rebornix.ruby
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - mhutchie.git-graph
