tasks:
  - init: |
      docker-compose pull
      docker-compose build
      docker-compose run --rm backend yarn install
      docker-compose run --rm backend bundle exec rails db:setup
  - command: docker-compose up -d

ports:
  - port: 3000
    visibility: public
  - port: 3035
    visibility: private
  - port: 6379
    visibility: private
  - port: 5432
    visibility: private

vscode:
  extensions:
    - rebornix.ruby
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - mhutchie.git-graph
