image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      docker-compose up -d &&
      bundle install &&
      gem install foreman &&
      yarn install &&
      bundle exec rails db:setup &&
      bundle exec rails test

ports:
  - port: 3000
    visibility: public
  - port: 3035
    visibility: private
  - port: 6379
    visibility: private
  - port: 5432
    visibility: private

vscode:
  extensions:
    - rebornix.ruby
    - LoranKloeze.ruby-rubocop-revived
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - mhutchie.git-graph
