language: ruby
dist: trusty

cache: bundler

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database eventaservo_test;' -U postgres

bundler_args: --without production --jobs=3 --retry=3

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake
