codecov:
  branch: main
  notify:
    wait_for_ci: false
coverage:
  status:
    project: true
    project:
      default:
        target: auto
        threshold: 1%
  flags:
    minitest:
      paths:
        - "app/"
        - "test/"
    system_tests:
      paths:
        - "app/"
        - "test/"
  ignore:
    - lib
    - config
    - spec
