services:
  backend:
    environment:
      - EDITOR=code --wait
    volumes:
      - ./:/eventaservo:cached
      - ~/.ssh:/home/rails/.ssh:ro
      - ~/.config:/home/rails/.config

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  solid_queue:
    volumes:
      - ./:/eventaservo:cached
