version: '3.8'

services:
  backend:
    volumes:
      - ..:/workspaces:cached
      - ~/.ssh:/root/.ssh:ro

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
