# periodic_cleanup:
#   class: CleanSoftDeletedRecordsJob
#   queue: background
#   args: [ 1000, { batch_size: 500 } ]
#   schedule: every hour
# periodic_command:
#   command: "SoftDeletedRecord.due.delete_all"
#   priority: 2
#   schedule: at 5am every day
worker_heartbeat:
  class: WorkerHeartbeatJob
  schedule: every hour
sitemap_refresh:
  class: SitemapRefreshJob
  schedule: every 6 hours
backup_db:
  class: BackupDbJob
  schedule: every day at 5am
generate_statistics:
  class: GenerateStatisticsJob
  schedule: every day at 1am
housekeeping:
  class: HousekeepingJob
  schedule: every day at 0:30am
