# Sidekiq Cron jobs
worker_heartbeat:
  description: "Check if the worker is alive"
  cron: "* * * * *"
  class: "WorkerHeartbeatJob"
  queue: "default"

sitemap_refresh:
  description: "Refreshes the Sitemap and publishes it"
  cron: "0 */6 * * *"
  class: "SitemapRefreshJob"
  queue: "low"

daily_backup:
  description: "Daily backup of the database"
  cron: "0 5 * * *"
  class: "BackupDbJob"
  queue: "low"
