# Sidekiq Cron jobs
worker_heartbeat:
  description: "Check if the worker is alive"
  cron: "1 * * * *"
  class: "WorkerHeartbeatJob"

sitemap_refresh:
  description: "Refreshes the Sitemap and publishes it"
  cron: "0 */6 * * *"
  class: "SitemapRefreshJob"

daily_backup:
  description: "Daily backup of the database"
  cron: "0 5 * * *"
  class: "BackupDbJob"
