default: &default
  dispatchers:
    - polling_interval: 15
      batch_size: 500
  workers:
    - queues: "*"
      threads: 5
      processes: 1
      polling_interval: 15

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
