default: &default
  dispatchers:
    - polling_interval: 15
      batch_size: 500
      recurring_tasks:
        worker_heartbeat:
          class: WorkerHeartbeatJob
          schedule: "0 * * * *"
        sitemap_refresh:
          class: SitemapRefreshJob
          schedule: "0 */6 * * *" # Every 6 hours
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 15

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default

staging:
 <<: *default
