default: &default
  dispatchers:
    - polling_interval: 15
      batch_size: 500
      recurring_tasks:
        worker_heartbeat:
          class: WorkerHeartbeatJob
          schedule: "0 * * * *"
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 15

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default

staging:
 <<: *default
