# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Listo de landoj
['Afganio',
 'Alando',
 'Albanio',
 'Alĝerio',
 'Andoro',
 'Angolo',
 'Angvilo',
 'Antarktiko',
 'Antigvo-Barbudo',
 'Apostola Seĝo (Vatikano)',
 'Argentino',
 'Armenio',
 'Arubo',
 'Aŭstralio',
 'Aŭstrio',
 'Azerbajĝano',
 'Bahamoj',
 'Bangladeŝo',
 'Barato',
 'Barbado',
 'Barejno',
 'Belgio',
 'Belizo',
 'Belorusio',
 'Benino',
 'Bermudo',
 'Birmo',
 'Bocvano',
 'Bolivio',
 'Bosnio kaj Hercegovino',
 'Brazilo',
 'Brita Hindoceana Teritorio',
 'Britio',
 'Brunejo',
 'Bulgario',
 'Burkino',
 'Burundo',
 'Butano',
 'Buvet-Insulo',
 'Ĉadio',
 'Ĉeĥio',
 'Centr-Afrika Respubliko',
 'Ĉilio',
 'Ĉinio',
 'Danio',
 'Domingo',
 'Dominiko',
 'Ebur-Bordo',
 'Egiptio',
 'Ekvadoro',
 'Eritreo',
 'Estonio',
 'Etiopio',
 'Falklandaj Insuloj, Malvinoj',
 'Ferooj',
 'Fiĝioj',
 'Filipinoj',
 'Finnlando',
 'Franca Gujano',
 'Franca Polinezio',
 'Francaj Sudaj kaj Antarktaj Teritorioj',
 'Francio',
 'Gabono',
 'Gambio',
 'Ganao',
 'Germanio',
 'Ĝibraltaro',
 'Ĝibutio',
 'Grekio',
 'Grenado',
 'Gronlando',
 'Gujano',
 'Gvadelupo',
 'Gvamo',
 'Gvatemalo',
 'Gvernsejo',
 'Gvineo',
 'Gvineo Bisaŭa',
 'Gvineo Ekvatora',
 'Haitio',
 'Herda kaj Makdonaldaj Insuloj',
 'Hispanio',
 'Honduro',
 'Honkongo',
 'Hungario',
 'Indonezio',
 'Irako',
 'Irano',
 'Irlando',
 'Islando',
 'Israelo',
 'Italio',
 'Jamajko',
 'Japanio',
 'Jemeno',
 'Ĵersejo',
 'Jordanio',
 'Kaboverdo',
 'Kajmaninsuloj',
 'Kamboĝo',
 'Kameruno',
 'Kanado',
 'Kariba Nederlando',
 'Kartvelio',
 'Kataro',
 'Kazaĥio',
 'Kenjo',
 'Kipro',
 'Kirgizio',
 'Kiribato',
 'Kokosinsuloj',
 'Kolombio',
 'Komoroj',
 'Kongo',
 'Kongo (Demokratia Respubliko)',
 'Kostariko',
 'Kristnaskinsulo',
 'Kroatio',
 'Kubo',
 'Kukinsuloj',
 'Kuracao',
 'Kuvajto',
 'Laoso',
 'Latvio',
 'Lesoto',
 'Libano',
 'Liberio',
 'Libio',
 'Liĥtenŝtejno',
 'Litovio',
 'Luksemburgo',
 'Madagaskaro',
 'Majoto',
 'Makao',
 'Makedonio',
 'Malajzio',
 'Malavio',
 'Maldivoj',
 'Malio',
 'Malto',
 'Manksinsulo',
 'Maroko',
 'Marŝalaj Insuloj',
 'Martiniko',
 'Maŭricio',
 'Maŭritanio',
 'Meksiko',
 'Mikronezio',
 'Moldavio',
 'Monako',
 'Moncerato',
 'Mongolio',
 'Montenegro',
 'Mozambiko',
 'Namibio',
 'Nauro',
 'Nederlando',
 'Nepalo',
 'Niĝerio',
 'Niĝero',
 'Nikaragvo',
 'Niuo',
 'Nord-Koreio',
 'Nord-Marianoj',
 'Norfolkinsulo',
 'Norvegio',
 'Nov-Kaledonio',
 'Nov-Zelando',
 'Okcidenta Saharo',
 'Omano',
 'Pakistano',
 'Palaŭo',
 'Palestino',
 'Panamo',
 'Papuo-Nov-Gvineo',
 'Paragvajo',
 'Peruo',
 'Pitkarna Insularo',
 'Pollando',
 'Porto-Riko',
 'Portugalio',
 'Reunio',
 'Ruando',
 'Rumanio',
 'Rusio',
 'Salomonoj',
 'Salvadoro',
 'Samoo',
 'Samoo Usona (Orienta)',
 'San-Marino',
 'Sankta-Bartolomeo',
 'Sankta-Heleno',
 'Sankta-Kito kaj Neviso',
 'Sankta-Lucio',
 'Sankta-Marteno (Franca parto)',
 'Sankta-Marteno (Nederlanda parto)',
 'Sankta-Piero kaj Mikelono',
 'Sankta-Vincento kaj Grenadinoj',
 'Sao-Tomeo kaj Principeo',
 'Saŭda Arabio',
 'Sejŝeloj',
 'Senegalo',
 'Serbio',
 'Siera-Leono',
 'Singapuro',
 'Sirio',
 'Slovakio',
 'Slovenio',
 'Somalio',
 'Sri-Lanko',
 'Sud-Afriko',
 'Sud-Georgio kaj Sud-Sandviĉinsuloj',
 'Sud-Koreio',
 'Sud-Sudano',
 'Sudano',
 'Surinamo',
 'Svalbardo kaj Janmajeno',
 'Svazilando',
 'Svedio',
 'Svislando',
 'Taĝikio',
 'Tajlando',
 'Tajvano',
 'Tanzanio',
 'Timoro Orienta',
 'Togolando',
 'Tokelao',
 'Tongo',
 'Trinidado kaj Tobago',
 'Tunizio',
 'Turkio',
 'Turkmenio',
 'Turkoj kaj Kajkoj',
 'Tuvalo',
 'Ugando',
 'Ukrainio',
 'Unuiĝintaj Arabaj Emirlandoj',
 'Urugvajo',
 'Usonaj Malgrandaj Insuloj',
 'Usono',
 'Uzbekio',
 'Valiso kaj Futuno',
 'Vanuatuo',
 'Venezuelo',
 'Virgulininsuloj (Britaj)',
 'Virgulininsuloj (Usonaj)',
 'Vjetnamio',
 'Zambio',
 'Zimbabvo'].each do |country|
  Country.create!(name: country)
end
