# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Listo de landoj
[
  ["Santomeo kaj Principeo", 'Afriko'],
  ['Afganujo','Azio'],
  ['Albanujo', 'Eŭropo'],
  ['Alĝerio‎', 'Afriko'],
  ['Andoro', 'Eŭropo'],
  ['Angolo‎', 'Afriko'],
  ['Angvilo', 'Ameriko'],
  ['Antigvo kaj Barbudo‎', 'Ameriko'],
  ['Argentino', 'Ameriko'],
  ['Armenujo','Azio'],
  ['Arubo', 'Ameriko'],
  ['Azerbaj','Azio'],
  ['Aŭstralio‎', 'Oceanio'],
  ['Aŭstrujo‎ ', 'Eŭropo'],
  ['Bahamoj', 'Ameriko'],
  ['Banglade','Azio'],
  ['Barato','Azio'],
  ['Barbado', 'Ameriko'],
  ['Barejno','Azio'],
  ['Belgujo', 'Eŭropo'],
  ['Belizo', 'Ameriko'],
  ['Belorusujo', 'Eŭropo'],
  ['Benino‎', 'Afriko'],
  ['Bermudoj', 'Ameriko'],
  ['Birmo','Azio'],
  ['Bocvano‎', 'Afriko'],
  ['Bolivio', 'Ameriko'],
  ['Bonero', 'Ameriko'],
  ['Bosnujo kaj Hercegovino‎', 'Eŭropo'],
  ['Brazilo', 'Ameriko'],
  ['Britaj Virgulinsuloj‎', 'Ameriko'],
  ['Britujo', 'Eŭropo'],
  ['Brunejo','Azio'],
  ['Bulgarujo', 'Eŭropo'],
  ['Burkino‎', 'Afriko'],
  ['Burundo‎', 'Afriko'],
  ['Butano','Azio'],
  ['Centr-Afrika Respubliko‎', 'Afriko'],
  ['Centr-Afriko‎', 'Afriko'],
  ['Danujo', 'Eŭropo'],
  ['Dominika Respubliko‎', 'Ameriko'],
  ['Dominiko', 'Ameriko'],
  ['Ebur-Bordo‎', 'Afriko'],
  ['Egiptujo','Azio'],
  ['Egiptujo‎', 'Afriko'],
  ['Ekonomio de Karibaj Landoj‎', 'Ameriko'],
  ['Ekvadoro', 'Ameriko'],
  ['Ekvatora', 'Afriko'],
  ['Eritreo‎', 'Afriko'],
  ['Estonujo', 'Eŭropo'],
  ['Etiopujo‎', 'Afriko'],
  ['Falklandoj', 'Ameriko'],
  ['Ferooj', 'Eŭropo'],
  ['Filipinoj','Azio'],
  ['Finnlando', 'Eŭropo'],
  ['Fiĝio', 'Oceanio'],
  ['Franca Polinezio‎', 'Oceanio'],
  ['Franca', 'Ameriko'],
  ['Francujo', 'Eŭropo'],
  ['Gabono‎', 'Afriko'],
  ['Gambio‎', 'Afriko'],
  ['Ganao‎', 'Afriko'],
  ['Germanujo', 'Eŭropo'],
  ['Grekujo', 'Eŭropo'],
  ['Grenado', 'Ameriko'],
  ['Gronlando', 'Ameriko'],
  ['Gujano', 'Ameriko'],
  ['Gvadelupo', 'Ameriko'],
  ['Gvamo‎', 'Oceanio'],
  ['Gvatemalo','Ameriko'],
  ['Gvineo-Bisaŭo‎', 'Afriko'],
  ['Gvineo‎', 'Afriko'],
  ['Haitio', 'Ameriko'],
  ['Hispanujo', 'Eŭropo'],
  ['Honduro', 'Ameriko'],
  ['Honkongo','Azio'],
  ['Hungarujo', 'Eŭropo'],
  ['Indonezio','Azio'],
  ['Irako','Azio'],
  ['Irano','Azio'],
  ['Irlando', 'Eŭropo'],
  ['Islando', 'Eŭropo'],
  ['Israelo','Azio'],
  ['Italujo', 'Eŭropo'],
  ['Jamajko', 'Ameriko'],
  ['Japanujo','Azio'],
  ['Jemeno','Azio'],
  ['Jordanio','Azio'],
  ['Kaboverdo‎', 'Afriko'],
  ['Kamboĝo‎','Azio'],
  ['Kameruno‎', 'Afriko'],
  ['Kanado', 'Ameriko'],
  ['Karibaj Landoj‎', 'Ameriko'],
  ['Kartvelujo','Azio'],
  ['Kataro','Azio'],
  ['Kazaĥujo‎ ','Azio'],
  ['Kejmanoj', 'Ameriko'],
  ['Kenjo‎', 'Afriko'],
  ['Kipro', 'Eŭropo'],
  ['Kirgizujo','Azio'],
  ['Kiribato‎', 'Oceanio'],
  ['Kokosinsuloj','Azio'],
  ['Kolombio', 'Ameriko'],
  ['Komoroj‎', 'Afriko'],
  ['Kongo', 'Afriko'],
  ['Kongo (Demokratia Respubliko)', 'Afriko'],
  ['Kosovo', 'Eŭropo'],
  ['Kostariko', 'Ameriko'],
  ['Kristnaskinsulo','Azio'],
  ['Kroatujo', 'Eŭropo'],
  ['Kubo', 'Ameriko'],
  ['Kukinsuloj', 'Oceanio'],
  ['Kuracao', 'Ameriko'],
  ['Kuvajto','Azio'],
  ['Laoso','Azio'],
  ['Latvujo', 'Eŭropo'],
  ['Lesoto‎', 'Afriko'],
  ['Libano','Azio'],
  ['Liberio‎', 'Afriko'],
  ['Libio‎', 'Afriko'],
  ['Litovujo', 'Eŭropo'],
  ['Liĥtenŝtejno‎', 'Eŭropo'],
  ['Luksemburgo', 'Eŭropo'],
  ['Madagaskaro‎', 'Afriko'],
  ['Majoto‎', 'Afriko'],
  ['Makao','Azio'],
  ['Makedonujo', 'Eŭropo'],
  ['Malajzio','Azio'],
  ['Malavio‎', 'Afriko'],
  ['Maldivoj','Azio'],
  ['Malio‎', 'Afriko'],
  ['Malto', 'Eŭropo'],
  ['Maroko‎', 'Afriko'],
  ['Martiniko', 'Ameriko'],
  ['Marŝaloj‎', 'Oceanio'],
  ['Maŭricio‎', 'Afriko'],
  ['Maŭritanio‎', 'Afriko'],
  ['Meksiko', 'Ameriko'],
  ['Mikronezio', 'Oceanio'],
  ['Moldavujo', 'Eŭropo'],
  ['Monako', 'Eŭropo'],
  ['Moncerato', 'Ameriko'],
  ['Mongolujo','Azio'],
  ['Montenegro', 'Eŭropo'],
  ['Mozambiko‎', 'Afriko'],
  ['Namibio‎', 'Afriko'],
  ['Nauro‎', 'Oceanio'],
  ['Nederlando', 'Eŭropo'],
  ['Nepalo','Azio'],
  ['Nikaragvo', 'Ameriko'],
  ['Niuo', 'Oceanio'],
  ['Niĝerio‎', 'Afriko'],
  ['Niĝero‎', 'Afriko'],
  ['Nord-Koreujo','Azio'],
  ['Nord-Marianoj‎', 'Oceanio'],
  ['Norfolkinsulo‎', 'Oceanio'],
  ['Norvegujo', 'Eŭropo'],
  ['Nov-Kaledonio‎', 'Oceanio'],
  ['Nov-Zelando', 'Oceanio'],
  ['Okcidenta Saharo‎', 'Afriko'],
  ['Omano','Azio'],
  ['Orienta','Azio'],
  ['Pakistano','Azio'],
  ['Palaŭo‎', 'Oceanio'],
  ['Palestino','Azio'],
  ['Panamo', 'Ameriko'],
  ['Papuo-Nov-Gvineo', 'Oceanio'],
  ['Paragvajo', 'Ameriko'],
  ['Peruo', 'Ameriko'],
  ['Pitkarna Insulo‎', 'Oceanio'],
  ['Pollando', 'Eŭropo'],
  ['Portugalujo', 'Eŭropo'],
  ['Puertoriko', 'Ameriko'],
  ['Reunio‎', 'Afriko'],
  ['Ruando‎', 'Afriko'],
  ['Rumanujo', 'Eŭropo'],
  ['Rusujo', 'Eŭropo'],
  ['Rusujo (azia parto)','Azio'],
  ['Salomonoj‎', 'Oceanio'],
  ['Salvadoro', 'Ameriko'],
  ['Samoo', 'Oceanio'],
  ['Sankta Bartolomeo‎', 'Ameriko'],
  ['Sankta Heleno‎', 'Afriko'],
  ['Sankta Kristoforo kaj Neviso‎', 'Ameriko'],
  ['Sankta Lucio‎', 'Ameriko'],
  ['Sankta Marteno‎', 'Ameriko'],
  ['Sankta Piero kaj Mikelono‎', 'Ameriko'],
  ['Sankta Vincento kaj Grenadinoj‎', 'Ameriko'],
  ['Sanmarino', 'Eŭropo'],
  ['Sauda','Azio'],
  ['Sejŝeloj‎', 'Afriko'],
  ['Senegalo‎', 'Afriko'],
  ['Serbujo', 'Eŭropo'],
  ['Sieraleono‎', 'Afriko'],
  ['Singapuro','Azio'],
  ['Sirio','Azio'],
  ['Slovakujo', 'Eŭropo'],
  ['Slovenujo', 'Eŭropo'],
  ['Somalujo‎', 'Afriko'],
  ['Srilanko','Azio'],
  ['Sud-Afriko‎', 'Afriko'],
  ['Sud-Georgio kaj Sud-Sandviĉinsuloj‎', 'Ameriko'],
  ['Sud-Koreujo‎','Azio'],
  ['Sud-Sudano‎', 'Afriko'],
  ['Sudano‎', 'Afriko'],
  ['Surinamo', 'Ameriko'],
  ['Svalbardo kaj Janmajeno‎', 'Eŭropo'],
  ['Svazilando‎', 'Afriko'],
  ['Svedujo', 'Eŭropo'],
  ['Svislando', 'Eŭropo'],
  ['Tajlando','Azio'],
  ['Tajvano','Azio'],
  ['Tanzanio‎', 'Afriko'],
  ['Taĝikujo‎ ','Azio'],
  ['Togolando‎', 'Afriko'],
  ['Tokelao‎', 'Oceanio'],
  ['Tongo', 'Oceanio'],
  ['Trinidado kaj Tobago‎', 'Ameriko'],
  ['Tunizio‎', 'Afriko'],
  ['Turkmenujo','Azio'],
  ['Turkoj kaj Kajkoj‎', 'Ameriko'],
  ['Turkujo', 'Eŭropo'],
  ['Tuvalo‎', 'Oceanio'],
  ['Ugando‎', 'Afriko'],
  ['Ukrainujo', 'Eŭropo'],
  ['Unuiĝintaj Arabaj Emirlandoj‎ ','Azio'],
  ['Urugvajo', 'Ameriko'],
  ['Usona Samoo‎', 'Oceanio'],
  ['Usonaj malgrandaj insuloj‎', 'Oceanio'],
  ['Usonaj Virgulinsuloj‎', 'Ameriko'],
  ['Usono', 'Ameriko'],
  ['Uzbekujo','Azio'],
  ['Valiso kaj Futuno‎', 'Oceanio'],
  ['Vanuatuo', 'Oceanio'],
  ['Vatikano', 'Eŭropo'],
  ['Venezuelo', 'Ameriko'],
  ['Virgulinsuloj', 'Ameriko'],
  ['Zambio‎', 'Afriko'],
  ['Zimbabvo‎', 'Afriko'],
  ['Ĉado‎', 'Afriko'],
  ['Ĉagosarkipelago‎','Azio'],
  ['Ĉeĥujo‎', 'Eŭropo'],
  ['Ĉilio‎', 'Ameriko'],
  ['Ĉinujo‎','Azio'],
  ['Ĝibraltaro‎', 'Eŭropo'],
  ['Ĝibutio‎', 'Afriko']
].each do |country, continent|
  Country.create!(name: country, continent: continent)
end
