name: End-to-end tests
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: start docker-compose services
        run: docker-compose -f docker-compose.ci.yml up -d --build
        env:
          CYPRESS_BASE_URL: https://localhost:3000

