name: End-to-end tests
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: eventaservo_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/checkout@v3

      - name: Ruby 3.0 e Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Yarn
        run: yarn install

      - name: Start Rails server
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.rails_master_key }}
        run: |
          bin/rails assets:precompile
          bin/rails db:migrate
          bin/rails db:seed
          bin/rails bin/rails server -d -u Puma -b 0.0.0.0 -p 3000 -e test -b 'ssl://0.0.0.0:3000?key=./certs/localhost.key&cert=./certs/localhost.crt'

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
