name: Deploy to staging

on:
  push:
    branches:
      - staging
    tags:
      - staging

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      environment: staging
      tag: staging
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

  sentry:
    needs: docker
    uses: ./.github/workflows/sentry.yml
    with:
      environment: staging
    secrets:
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}

  Portainer:
    needs: docker
    runs-on: ubuntu-22.04
    steps:
      - name: Update Docker Swarm on Portainer
        run: |
          curl -k -X POST ${{ secrets.PORTAINER_WEBHOOK_STAGING }}
