name: Staging deploy

on:
  push:
    branches:
      - staging
    tags:
      - staging

jobs:
  minitest:
    uses: eventaservo/eventaservo/.github/workflows/template_test.yml@main
    secrets:
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docker:
    needs: minitest
    uses: eventaservo/eventaservo/.github/workflows/docker.yml@main
    with:
      environment: staging
      tag: staging
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

  sentry:
    needs: docker
    uses: eventaservo/eventaservo/.github/workflows/sentry.yml@main
    with:
      environment: 'staging'
    secrets:
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
