name: Staging deploy

on:
  push:
    branches:
      - staging
    tags:
      - staging

jobs:
  minitest:
    uses: ./.github/workflows/template_test.yml
    secrets:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docker:
    needs: minitest
    uses: ./.github/workflows/docker.yml
    with:
      environment: staging
      tag: staging
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

  sentry:
    needs: docker
    uses: ./.github/workflows/sentry.yml
    with:
      environment: staging
    secrets:
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}

  update_swarm:
    needs: docker
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Update swarm
        uses: appleboy/ssh-action@master
        with:
          host: svr3.bahai.org.br
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: /docker/eventaservo/staging/update.sh
