name: Standard Ruby

on: [pull_request]

jobs:
  checker:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
    steps:
      - name: Standard Ruby
        uses: standardrb/standard-ruby-action@eecb3f730879f5b8830705348c2961e5aa26de78 # v1
