name: Standard Ruby

on: [pull_request]

jobs:
  checker:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
    steps:
      - name: Standard Ruby
        uses: standardrb/standard-ruby-action@df5152f6106147e13feb6ee0fa820b0d435cb8cd # v1
